server:
  port: 8765

postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: local-dev-placeholder
  dbname: yasumi
  sslmode: disable

jwt:
  secret: local-dev-placeholder
  expireHour: 24
